# Generated by Django 2.2.13 on 2025-12-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20210314_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_nested',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0, verbose_name='是否二级页面监控'),
        ),
        migrations.AddField(
            model_name='task',
            name='nested_selector_type',
            field=models.IntegerField(choices=[(0, 'Xpath'), (1, 'Css selector'), (2, 'JsonPath')], default=0, verbose_name='二级页面URL选择器类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='nested_url_selector',
            field=models.CharField(blank=True, help_text='只支持一个元素选择器，用于提取二级页面的URL。如果是Xpath，请确保提取的是href属性，例如：//*[@id="id3"]/a/@href', max_length=500, verbose_name='二级页面URL选择器'),
        ),
    ]
